# Generated by Django 2.2 on 2019-06-13 12:14

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('secretary', 'secretary'), ('instructor', 'instructor'), ('students', 'students')], max_length=25)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_hour', models.IntegerField(default=0)),
                ('lessons', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(default=None, limit_choices_to={'role': 'secretary'}, on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='driving_school.CustomUser')),
                ('user', models.ForeignKey(default=None, limit_choices_to={'role': 'students'}, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='driving_school.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('location', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(limit_choices_to=models.Q(('role', 'secretary'), ('role', 'instructor'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='driving_school.CustomUser')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'students'}, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='driving_school.CustomUser')),
            ],
        ),
    ]
