# Generated by Django 2.2.2 on 2019-06-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='student',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'students'}, on_delete=django.db.models.deletion.CASCADE, related_name='tata', to='driving_school.CustomUser'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='owner',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('role', 'secretary'), ('role', 'instructor'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='toto', to='driving_school.CustomUser'),
        ),
    ]
