# Generated by Django 2.2 on 2019-06-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0002_auto_20190611_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='planning',
            name='owner',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'secretary'), ('role', 'instructor'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='driving_school.User'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'students'}, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='driving_school.User'),
        ),
    ]
