# Generated by Django 2.2.2 on 2019-06-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0002_auto_20190612_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='student',
        ),
        migrations.AddField(
            model_name='userplan',
            name='creator',
            field=models.ForeignKey(default=None, limit_choices_to='secretary', on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='driving_school.CustomUser'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='user',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'students'}, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='driving_school.CustomUser'),
        ),
    ]
