# Generated by Django 2.2.2 on 2019-06-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0005_auto_20190613_1410'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
